/**
 * Dashboard Page
 * Generated by Worldbuilder
 */

import { useQuery } from '@tanstack/react-query';
import {
  Box,
  Grid,
  Paper,
  Typography,
  Card,
  CardContent,
  CircularProgress,
} from '@mui/material';
import {
  Inbox as TagIcon,
  Category as CategoryIcon,
  Person as UserIcon,
  CheckCircle as TaskIcon,
} from '@mui/icons-material';
import { api } from '../lib/api-client';

export function DashboardPage() {
  const { data: tagData } = useQuery({
    queryKey: ['tag-count'],
    queryFn: () => api.tag.getAll({ page: 1, limit: 1 }),
  });
  const { data: categoryData } = useQuery({
    queryKey: ['category-count'],
    queryFn: () => api.category.getAll({ page: 1, limit: 1 }),
  });
  const { data: taskData } = useQuery({
    queryKey: ['task-count'],
    queryFn: () => api.task.getAll({ page: 1, limit: 1 }),
  });

  const stats = [
    {
      title: 'Tags',
      value: tagData?.pagination.total || 0,
      icon: <TagIcon sx={{ fontSize: 40 }} />,
      color: 'primary',
    },
    {
      title: 'Categories',
      value: categoryData?.pagination.total || 0,
      icon: <CategoryIcon sx={{ fontSize: 40 }} />,
      color: 'secondary',
    },
    {
      title: 'Tasks',
      value: taskData?.pagination.total || 0,
      icon: <TaskIcon sx={{ fontSize: 40 }} />,
      color: 'info',
    },
  ];

  return (
    <Box>
      <Typography variant="h4" fontWeight={700} mb={3}>
        Dashboard
      </Typography>

      <Grid container spacing={3}>
        {stats.map((stat, index) => (
          <Grid item xs={12} sm={6} md={3} key={index}>
            <Card>
              <CardContent>
                <Box display="flex" justifyContent="space-between" alignItems="center">
                  <Box>
                    <Typography variant="body2" color="text.secondary" gutterBottom>
                      {stat.title}
                    </Typography>
                    <Typography variant="h4" fontWeight={700}>
                      {stat.value}
                    </Typography>
                  </Box>
                  <Box
                    sx={{
                      width: 64,
                      height: 64,
                      borderRadius: 2,
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      bgcolor: `$\{stat.color}.50`,
                      color: `$\{stat.color}.main`,
                    }}
                  >
                    {stat.icon}
                  </Box>
                </Box>
              </CardContent>
            </Card>
          </Grid>
        ))}
      </Grid>

      <Grid container spacing={3} mt={2}>
        <Grid item xs={12} md={6}>
          <Paper sx={{ p: 3 }}>
            <Typography variant="h6" fontWeight={600} gutterBottom>
              Welcome to Todo API
            </Typography>
            <Typography variant="body2" color="text.secondary">
              Your application dashboard. Use the navigation menu to manage your data.
            </Typography>
          </Paper>
        </Grid>

        <Grid item xs={12} md={6}>
          <Paper sx={{ p: 3 }}>
            <Typography variant="h6" fontWeight={600} gutterBottom>
              Quick Stats
            </Typography>
            <Box mt={2}>
              <Box display="flex" justifyContent="space-between" mb={1}>
                <Typography variant="body2" color="text.secondary">
                  Total Tags
                </Typography>
                <Typography variant="body2" fontWeight={600}>
                  {{{camelCase name}}Data?.pagination.total || 0}
                </Typography>
              </Box>
              <Box display="flex" justifyContent="space-between" mb={1}>
                <Typography variant="body2" color="text.secondary">
                  Total Categories
                </Typography>
                <Typography variant="body2" fontWeight={600}>
                  {{{camelCase name}}Data?.pagination.total || 0}
                </Typography>
              </Box>
              <Box display="flex" justifyContent="space-between" mb={1}>
                <Typography variant="body2" color="text.secondary">
                  Total Tasks
                </Typography>
                <Typography variant="body2" fontWeight={600}>
                  {{{camelCase name}}Data?.pagination.total || 0}
                </Typography>
              </Box>
            </Box>
          </Paper>
        </Grid>
      </Grid>
    </Box>
  );
}

