/**
 * Type-safe API Client
 * Generated by Worldbuilder
 */

import axios, { AxiosInstance, AxiosRequestConfig } from 'axios';

// Types
export interface Tag {
  id: string;
  name: string;
  color?: string;
  createdAt: string;
  updatedAt: string;
}

export interface CreateTagInput {
  name: string;
  color?: string;
}

export interface UpdateTagInput {
  name?: string;
  color?: string;
}

export interface Category {
  id: string;
  name: string;
  description?: string;
  createdAt: string;
  updatedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface CreateCategoryInput {
  name: string;
  description?: string;
  createdAt: string;
  updatedAt: string;
}

export interface UpdateCategoryInput {
  name?: string;
  description?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface User {
  id: string;
  username: string;
  email: string;
  password: string;
  createdAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface CreateUserInput {
  username: string;
  email: string;
  password: string;
}

export interface UpdateUserInput {
  username?: string;
  email?: string;
  password?: string;
}

export interface Task {
  id: string;
  createdAt: string;
  updatedAt: string;
}

export interface CreateTaskInput {
}

export interface UpdateTaskInput {
}


// Pagination
export interface PaginatedResponse<T> {
  data: T[];
  pagination: {
    page: number;
    limit: number;
    total: number;
    pages: number;
  };
}

// API Client Class
class ApiClient {
  private client: AxiosInstance;

  constructor(baseURL: string = import.meta.env.VITE_API_URL || 'http://localhost:3001') {
    this.client = axios.create({
      baseURL,
      headers: {
        'Content-Type': 'application/json',
      },
    });

    // Add auth token to requests
    this.client.interceptors.request.use((config) => {
      const token = localStorage.getItem('auth_token');
      if (token) {
        config.headers.Authorization = `Bearer ${token}`;
      }
      return config;
    });

    // Handle auth errors
    this.client.interceptors.response.use(
      (response) => response,
      (error) => {
        if (error.response?.status === 401) {
          localStorage.removeItem('auth_token');
          window.location.href = '/login';
        }
        return Promise.reject(error);
      }
    );
  }

  // Tag API
  tag = {
    getAll: async (params?: { page?: number; limit?: number; include?: boolean }): Promise<PaginatedResponse<Tag>> => {
      const response = await this.client.get('/tag', { 
        params: {
          ...params,
          include: params?.include !== false, // Default to true
        }
      });
      return response.data;
    },

    getById: async (id: string, include: boolean = true): Promise<Tag> => {
      const response = await this.client.get(`/tag/${id}`, {
        params: { include }
      });
      return response.data;
    },

    create: async (data: CreateTagInput): Promise<Tag> => {
      const response = await this.client.post('/tag', data);
      return response.data;
    },

    update: async (id: string, data: UpdateTagInput): Promise<Tag> => {
      const response = await this.client.patch(`/tag/${id}`, data);
      return response.data;
    },

    delete: async (id: string): Promise<void> => {
      await this.client.delete(`/tag/${id}`);
    },

    // Relationship helpers

    // Get all  for dropdowns
  };

  // Category API
  category = {
    getAll: async (params?: { page?: number; limit?: number; include?: boolean }): Promise<PaginatedResponse<Category>> => {
      const response = await this.client.get('/category', { 
        params: {
          ...params,
          include: params?.include !== false, // Default to true
        }
      });
      return response.data;
    },

    getById: async (id: string, include: boolean = true): Promise<Category> => {
      const response = await this.client.get(`/category/${id}`, {
        params: { include }
      });
      return response.data;
    },

    create: async (data: CreateCategoryInput): Promise<Category> => {
      const response = await this.client.post('/category', data);
      return response.data;
    },

    update: async (id: string, data: UpdateCategoryInput): Promise<Category> => {
      const response = await this.client.patch(`/category/${id}`, data);
      return response.data;
    },

    delete: async (id: string): Promise<void> => {
      await this.client.delete(`/category/${id}`);
    },

  };

  // Task API
  task = {
    getAll: async (params?: { page?: number; limit?: number; include?: boolean }): Promise<PaginatedResponse<Task>> => {
      const response = await this.client.get('/task', { 
        params: {
          ...params,
          include: params?.include !== false, // Default to true
        }
      });
      return response.data;
    },

    getById: async (id: string, include: boolean = true): Promise<Task> => {
      const response = await this.client.get(`/task/${id}`, {
        params: { include }
      });
      return response.data;
    },

    create: async (data: CreateTaskInput): Promise<Task> => {
      const response = await this.client.post('/task', data);
      return response.data;
    },

    update: async (id: string, data: UpdateTaskInput): Promise<Task> => {
      const response = await this.client.patch(`/task/${id}`, data);
      return response.data;
    },

    delete: async (id: string): Promise<void> => {
      await this.client.delete(`/task/${id}`);
    },

  };


  // Generic request method
  async request<T>(config: AxiosRequestConfig): Promise<T> {
    const response = await this.client.request<T>(config);
    return response.data;
  }
}

// Export singleton instance
export const api = new ApiClient();

