/**
 * App Router Configuration
 * Generated by Worldbuilder
 */

import { createBrowserRouter, Navigate } from 'react-router-dom';
import { AppLayout } from '../layouts/AppLayout';
import { LoginPage } from '../auth/LoginPage';
import { DashboardPage } from '../dashboard/DashboardPage';
import { TagListPage } from '../pages/TagListPage';
import { TagDetailPage } from '../pages/TagDetailPage';
import { TagFormPage } from '../pages/TagFormPage';
import { CategoryListPage } from '../pages/CategoryListPage';
import { CategoryDetailPage } from '../pages/CategoryDetailPage';
import { CategoryFormPage } from '../pages/CategoryFormPage';
import { TaskListPage } from '../pages/TaskListPage';
import { TaskDetailPage } from '../pages/TaskDetailPage';
import { TaskFormPage } from '../pages/TaskFormPage';

// Protected Route wrapper
function ProtectedRoute({ children }: { children: React.ReactNode }) {
  const token = localStorage.getItem('auth_token');
  if (!token) {
    return <Navigate to="/login" replace />;
  }
  return <>{children}</>;
}

export const router = createBrowserRouter([
  {
    path: '/login',
    element: <LoginPage />,
  },
  {
    path: '/',
    element: (
      <ProtectedRoute>
        <AppLayout />
      </ProtectedRoute>
    ),
    children: [
      {
        index: true,
        element: <DashboardPage />,
      },
      {
        path: 'tag',
        element: <TagListPage />,
      },
      {
        path: 'tag/new',
        element: <TagFormPage />,
      },
      {
        path: 'tag/:id',
        element: <TagDetailPage />,
      },
      {
        path: 'tag/:id/edit',
        element: <TagFormPage />,
      },
      {
        path: 'category',
        element: <CategoryListPage />,
      },
      {
        path: 'category/new',
        element: <CategoryFormPage />,
      },
      {
        path: 'category/:id',
        element: <CategoryDetailPage />,
      },
      {
        path: 'category/:id/edit',
        element: <CategoryFormPage />,
      },
      {
        path: 'task',
        element: <TaskListPage />,
      },
      {
        path: 'task/new',
        element: <TaskFormPage />,
      },
      {
        path: 'task/:id',
        element: <TaskDetailPage />,
      },
      {
        path: 'task/:id/edit',
        element: <TaskFormPage />,
      },
    ],
  },
]);

