import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { PrismaClient } from '@prisma/client';
import { TaskAuditor } from '../task-auditor.auditor';

/**
 * Unit Tests for TaskAuditor Auditor
 * Generated by Worldbuilder
 * 
 * 
 */

describe('TaskAuditor Auditor', () => {
  let prisma: PrismaClient;
  let auditor: TaskAuditor;
  const testUserId = 'test-user-id';

  beforeEach(async () => {
    prisma = new PrismaClient();
    auditor = new TaskAuditor(prisma);
    
    // Clean up test data
    await prisma.auditLog.deleteMany({});
  });

  afterEach(async () => {
    await prisma.$disconnect();
  });

  describe('beforeCreate Validation', () => {
    it('should validate valid data', async () => {
      const validData = {
        // Valid  data
        test: true,
      };

      await expect(
        auditor.beforeCreate(validData)
      ).resolves.not.toThrow();
    });

  });

  describe('afterCreate Audit Logging', () => {
    it('should create audit log after entity creation', async () => {
      const entity = {
        id: 'test-id',
        name: 'Test Entity',
      };

      await auditor.afterCreate(entity, testUserId);

      const logs = await prisma.auditLog.findMany({
        where: {
          entityId: entity.id,
          action: 'CREATE',
        },
      });

      expect(logs).toHaveLength(1);
      expect(logs[0].userId).toBe(testUserId);
    });
  });

  describe('beforeUpdate Validation', () => {
    it('should validate updates', async () => {
      const existing = { id: 'test-id', name: 'Original' };
      const updates = { name: 'Updated' };

      await expect(
        auditor.beforeUpdate(existing, updates)
      ).resolves.not.toThrow();
    });
  });

  describe('afterUpdate Audit Logging', () => {
    it('should log updates with before/after state', async () => {
      const before = { id: 'test-id', name: 'Original' };
      const after = { id: 'test-id', name: 'Updated' };

      await auditor.afterUpdate(before, after, testUserId);

      const logs = await prisma.auditLog.findMany({
        where: {
          entityId: after.id,
          action: 'UPDATE',
        },
      });

      expect(logs).toHaveLength(1);
      expect(logs[0].before).toEqual(before);
      expect(logs[0].after).toEqual(after);
    });
  });

  describe('Audit Log Query', () => {
    it('should retrieve audit logs for entity', async () => {
      const entityId = 'test-entity-id';
      
      // Create some audit logs
      await auditor.afterCreate({ id: entityId }, testUserId);
      
      const logs = await auditor.getAuditLogs(entityId);

      expect(logs.length).toBeGreaterThan(0);
      expect(logs[0].entityId).toBe(entityId);
    });
  });
});

