import { Router } from 'express';
import { PrismaClient } from '@prisma/client';
import { z } from 'zod';
import type { AuthRequest } from '../middleware/auth.js';
import { GitHubService } from '../services/GitHubService.js';
import { CodeGeneratorService } from '../services/CodeGenerator.service.js';

const router = Router();
const prisma = new PrismaClient();
const codeGenerator = new CodeGeneratorService();

const PushToGitHubSchema = z.object({
  projectId: z.string().uuid(),
  repoName: z.string().min(1),
  isPrivate: z.boolean().optional(),
  githubToken: z.string().min(1),
});

// POST /api/deploy/github - Push code to GitHub
router.post('/github', async (req: AuthRequest, res): Promise<void> => {
  try {
    const { projectId, repoName, isPrivate, githubToken } = PushToGitHubSchema.parse(req.body);

    // Verify project belongs to user
    const project = await prisma.project.findFirst({
      where: {
        id: projectId,
        userId: req.user!.id,
      },
    });

    if (!project) {
      res.status(404).json({ error: 'Project not found' });
      return;
    }

    // Initialize GitHub service
    const githubService = new GitHubService();
    githubService.initializeWithToken(githubToken);

    // Get user info
    const githubUser = await githubService.getUser();

    // Check if repository exists
    const existingRepos = await githubService.listRepositories();
    const existingRepo = existingRepos.find(
      (r) => r.name === repoName && r.owner.login === githubUser.login
    );

    let repo;
    if (existingRepo) {
      repo = existingRepo;
    } else {
      // Create repository
      repo = await githubService.createRepository(
        repoName,
        project.description || `Generated by Worldbuilder`,
        isPrivate || false
      );
    }

    // Generate code files
    const files = await codeGenerator.generateProject(projectId);

    // Push files to GitHub
    const result = await githubService.pushFiles(
      githubUser.login,
      repo.name,
      files,
      '🚀 Initial commit from Worldbuilder'
    );

    // Update project with GitHub repo URL
    await prisma.project.update({
      where: { id: projectId },
      data: { githubRepo: repo.html_url },
    });

    res.json({
      message: 'Code pushed to GitHub successfully',
      repoUrl: repo.html_url,
      commitSha: result.commitSha,
      commitUrl: result.commitUrl,
    });
  } catch (error: any) {
    console.error('Error pushing to GitHub:', error);
    res.status(500).json({ error: error.message || 'Failed to push to GitHub' });
  }
});

// POST /api/deploy/railway - Deploy to Railway
router.post('/railway', async (_req: AuthRequest, res): Promise<void> => {
  try {
    // TODO: Implement Railway integration
    res.json({ message: 'Railway deployment coming soon' });
  } catch (error) {
    console.error('Error deploying to Railway:', error);
    res.status(500).json({ error: 'Failed to deploy to Railway' });
  }
});

export { router as deployRouter };

