import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { PrismaClient } from '@prisma/client';
import { CategoryService } from '../category.service';
import { CreateCategoryDto, UpdateCategoryDto } from '../category.entity';

/**
 * Unit Tests for Category Service
 * Generated by Worldbuilder
 * 
 * 
 */

describe('Category Service', () => {
  let prisma: PrismaClient;
  let service: CategoryService;
  const testUserId = 'test-user-id';

  beforeEach(async () => {
    prisma = new PrismaClient();
    service = new CategoryService(prisma);
    
    // Clean up test data
    await prisma.category.deleteMany({});
  });

  afterEach(async () => {
    await prisma.$disconnect();
  });

  describe('create', () => {
    it('should create category with valid data', async () => {
      const createDto: CreateCategoryDto = {
        name: 'Test Name',
        description: 'Test Description',
        createdAt: null,
        updatedAt: null,
      };

      const result = await service.create(createDto, testUserId);

      expect(result.id).toBeDefined();
      expect(result.name).toBe(createDto.name);
      expect(result.description).toBe(createDto.description);
      expect(result.createdAt).toBe(createDto.createdAt);
      expect(result.updatedAt).toBe(createDto.updatedAt);
    });

    it('should reject missing name', async () => {
      const invalidDto: any = {
        name: 'Test',
        description: 'Test',
        createdAt: null,
        updatedAt: null,
      };

      await expect(
        service.create(invalidDto, testUserId)
      ).rejects.toThrow();
    });

    it('should reject missing createdAt', async () => {
      const invalidDto: any = {
        name: 'Test',
        description: 'Test',
        createdAt: null,
        updatedAt: null,
      };

      await expect(
        service.create(invalidDto, testUserId)
      ).rejects.toThrow();
    });

    it('should reject missing updatedAt', async () => {
      const invalidDto: any = {
        name: 'Test',
        description: 'Test',
        createdAt: null,
        updatedAt: null,
      };

      await expect(
        service.create(invalidDto, testUserId)
      ).rejects.toThrow();
    });

  });

  describe('findById', () => {
    it('should find existing category', async () => {
      const created = await service.create({
        name: 'Test Name',
        description: 'Test Description',
        createdAt: null,
        updatedAt: null,
      }, testUserId);

      const found = await service.findById(created.id);

      expect(found).not.toBeNull();
      expect(found?.id).toBe(created.id);
    });

    it('should return null for non-existent category', async () => {
      const found = await service.findById('non-existent-id');
      expect(found).toBeNull();
    });
  });

  describe('update', () => {
    it('should update category', async () => {
      const created = await service.create({
        name: 'Original',
        description: 'Original',
        createdAt: null,
        updatedAt: null,
      }, testUserId);

      const updateDto: UpdateCategoryDto = {
        name: 'Updated',
      };

      const updated = await service.update(created.id, updateDto, testUserId);

      expect(updated.name).toBe(updateDto.name);
    });

    it('should throw error for non-existent category', async () => {
      await expect(
        service.update('non-existent-id', {}, testUserId)
      ).rejects.toThrow('Category not found');
    });
  });

  describe('delete', () => {
    it('should delete category', async () => {
      const created = await service.create({
        name: 'Test',
        description: 'Test',
        createdAt: null,
        updatedAt: null,
      }, testUserId);

      await service.delete(created.id, testUserId);

      const found = await service.findById(created.id);
      expect(found).toBeNull();
    });

    it('should throw error for non-existent category', async () => {
      await expect(
        service.delete('non-existent-id', testUserId)
      ).rejects.toThrow('Category not found');
    });
  });

  describe('findAll', () => {
    it('should return empty array when no categories exist', async () => {
      const result = await service.findAll({});
      expect(result).toHaveLength(0);
    });

    it('should return all categories', async () => {
      await service.create({
        name: 'Test 1',
        description: 'Test 1',
        createdAt: null,
        updatedAt: null,
      }, testUserId);

      await service.create({
        name: 'Test 2',
        description: 'Test 2',
        createdAt: null,
        updatedAt: null,
      }, testUserId);

      const result = await service.findAll({});
      expect(result).toHaveLength(2);
    });
  });
});

