import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { PrismaClient } from '@prisma/client';
import { TaskService } from '../task.service';
import { CreateTaskDto, UpdateTaskDto } from '../task.entity';

/**
 * Unit Tests for Task Service
 * Generated by Worldbuilder
 * 
 * 
 */

describe('Task Service', () => {
  let prisma: PrismaClient;
  let service: TaskService;
  const testUserId = 'test-user-id';

  beforeEach(async () => {
    prisma = new PrismaClient();
    service = new TaskService(prisma);
    
    // Clean up test data
    await prisma.task.deleteMany({});
  });

  afterEach(async () => {
    await prisma.$disconnect();
  });

  describe('create', () => {
    it('should create task with valid data', async () => {
      const createDto: CreateTaskDto = {
      };

      const result = await service.create(createDto, testUserId);

      expect(result.id).toBeDefined();
    });

  });

  describe('findById', () => {
    it('should find existing task', async () => {
      const created = await service.create({
      }, testUserId);

      const found = await service.findById(created.id);

      expect(found).not.toBeNull();
      expect(found?.id).toBe(created.id);
    });

    it('should return null for non-existent task', async () => {
      const found = await service.findById('non-existent-id');
      expect(found).toBeNull();
    });
  });

  describe('update', () => {
    it('should update task', async () => {
      const created = await service.create({
      }, testUserId);

      const updateDto: UpdateTaskDto = {
      };

      const updated = await service.update(created.id, updateDto, testUserId);

    });

    it('should throw error for non-existent task', async () => {
      await expect(
        service.update('non-existent-id', {}, testUserId)
      ).rejects.toThrow('Task not found');
    });
  });

  describe('delete', () => {
    it('should delete task', async () => {
      const created = await service.create({
      }, testUserId);

      await service.delete(created.id, testUserId);

      const found = await service.findById(created.id);
      expect(found).toBeNull();
    });

    it('should throw error for non-existent task', async () => {
      await expect(
        service.delete('non-existent-id', testUserId)
      ).rejects.toThrow('Task not found');
    });
  });

  describe('findAll', () => {
    it('should return empty array when no tasks exist', async () => {
      const result = await service.findAll({});
      expect(result).toHaveLength(0);
    });

    it('should return all tasks', async () => {
      await service.create({
      }, testUserId);

      await service.create({
      }, testUserId);

      const result = await service.findAll({});
      expect(result).toHaveLength(2);
    });
  });
});

