import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { PrismaClient } from '@prisma/client';
import { UserService } from '../user.service';
import { CreateUserDto, UpdateUserDto } from '../user.entity';

/**
 * Unit Tests for User Service
 * Generated by Worldbuilder
 * 
 * 
 */

describe('User Service', () => {
  let prisma: PrismaClient;
  let service: UserService;
  const testUserId = 'test-user-id';

  beforeEach(async () => {
    prisma = new PrismaClient();
    service = new UserService(prisma);
    
    // Clean up test data
    await prisma.user.deleteMany({});
  });

  afterEach(async () => {
    await prisma.$disconnect();
  });

  describe('create', () => {
    it('should create user with valid data', async () => {
      const createDto: CreateUserDto = {
        username: 'Test Username',
        email: 'Test Email',
        password: 'Test Password',
      };

      const result = await service.create(createDto, testUserId);

      expect(result.id).toBeDefined();
      expect(result.username).toBe(createDto.username);
      expect(result.email).toBe(createDto.email);
      expect(result.password).toBe(createDto.password);
    });

    it('should reject missing username', async () => {
      const invalidDto: any = {
        username: 'Test',
        email: 'Test',
        password: 'Test',
      };

      await expect(
        service.create(invalidDto, testUserId)
      ).rejects.toThrow();
    });

    it('should reject missing email', async () => {
      const invalidDto: any = {
        username: 'Test',
        email: 'Test',
        password: 'Test',
      };

      await expect(
        service.create(invalidDto, testUserId)
      ).rejects.toThrow();
    });

    it('should reject missing password', async () => {
      const invalidDto: any = {
        username: 'Test',
        email: 'Test',
        password: 'Test',
      };

      await expect(
        service.create(invalidDto, testUserId)
      ).rejects.toThrow();
    });

  });

  describe('findById', () => {
    it('should find existing user', async () => {
      const created = await service.create({
        username: 'Test Username',
        email: 'Test Email',
        password: 'Test Password',
      }, testUserId);

      const found = await service.findById(created.id);

      expect(found).not.toBeNull();
      expect(found?.id).toBe(created.id);
    });

    it('should return null for non-existent user', async () => {
      const found = await service.findById('non-existent-id');
      expect(found).toBeNull();
    });
  });

  describe('update', () => {
    it('should update user', async () => {
      const created = await service.create({
        username: 'Original',
        email: 'Original',
        password: 'Original',
      }, testUserId);

      const updateDto: UpdateUserDto = {
        username: 'Updated',
      };

      const updated = await service.update(created.id, updateDto, testUserId);

      expect(updated.username).toBe(updateDto.username);
    });

    it('should throw error for non-existent user', async () => {
      await expect(
        service.update('non-existent-id', {}, testUserId)
      ).rejects.toThrow('User not found');
    });
  });

  describe('delete', () => {
    it('should delete user', async () => {
      const created = await service.create({
        username: 'Test',
        email: 'Test',
        password: 'Test',
      }, testUserId);

      await service.delete(created.id, testUserId);

      const found = await service.findById(created.id);
      expect(found).toBeNull();
    });

    it('should throw error for non-existent user', async () => {
      await expect(
        service.delete('non-existent-id', testUserId)
      ).rejects.toThrow('User not found');
    });
  });

  describe('findAll', () => {
    it('should return empty array when no users exist', async () => {
      const result = await service.findAll({});
      expect(result).toHaveLength(0);
    });

    it('should return all users', async () => {
      await service.create({
        username: 'Test 1',
        email: 'Test 1',
        password: 'Test 1',
      }, testUserId);

      await service.create({
        username: 'Test 2',
        email: 'Test 2',
        password: 'Test 2',
      }, testUserId);

      const result = await service.findAll({});
      expect(result).toHaveLength(2);
    });
  });
});

