import { describe, it, expect, beforeEach, afterEach, beforeAll } from 'vitest';
import request from 'supertest';
import { app } from '../../index';
import { PrismaClient } from '@prisma/client';

/**
 * Integration Tests for  API
 * Generated by Worldbuilder
 */

describe(' API', () => {
  let prisma: PrismaClient;
  let authToken: string;

  beforeAll(async () => {
    prisma = new PrismaClient();
    // TODO: Create test user and get auth token
    authToken = 'test-token';
  });

  afterAll(async () => {
    await prisma.$disconnect();
  });

  beforeEach(async () => {
    // Clean database before each test
    await prisma..deleteMany({});
  });





});

